### ISSUE TITLE
TSS column might be missing from region bed file

### ISSUE THREAD

**Issue by davidroberson** [GenEvoBioinfLab/rpgQTL#1]
![image](https://github.com/user-attachments/assets/3b35c110-10b3-4171-a39f-e69438c0d40e)

**Comment by davidroberson** [comment]
this is for the example jupyter notebook specifically.  thanks

**Comment by Jiahao-Gao** [comment]
I cannot reproduce this error. It might be related to pandas version. I have no problems with pandas 2.2.2

**Comment by davidroberson** [comment]
We were able to get this working with Pandas 2.2.2 and the updated rpy2 install readme using mamba.  Thanks

**Comment by davidroberson** [comment]
thanks for the new version of the software
